package task45;



//Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//        Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
//        Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
//        Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
//
//        It can be verified that T285 = P165 = H143 = 40755.
//
//        Find the next triangle number that is also pentagonal and hexagonal.


import static task45.AbstractGenerator.ITERATION_SIZE;

/**
 * Created by Pitrecki on 2016-10-07.
 */
public class Task45
{
    public static void main(String[] args) {
        AbstractGenerator triangleGen = new TriangleGenerator();
        AbstractGenerator pentaGen = new PentagonalGenerator();
//        AbstractGenerator hexaGen = new PentagonalGenerator();

        long startProgram = System.currentTimeMillis();
        for (int i = 1; i <= ITERATION_SIZE; i++) {
            triangleGen.addNumberToList(triangleGen.generate(i));
            pentaGen.addNumberToList(pentaGen.generate(i));
//            hexaGen.addNumberToList(hexaGen.generate(i));
        }

        for (Long trVal : triangleGen.getGeneratedNumbersList())
            for (Long pnVal : pentaGen.getGeneratedNumbersList())
//                for (Long heVal : hexaGen.getGeneratedNumbersList()) {
                    if (trVal.equals(pnVal))
                        System.out.println(trVal);






        long endProgram = System.currentTimeMillis();
        System.out.println("Time: " + (endProgram - startProgram)/1e3 + " s");
    }

}
